[package]
name = "ast"
version = "0.0.0"
description = "asts"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
# workspace deps

# local deps

# global deps
smol_str.workspace = true
